//AUTH ACTION
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const GET_ALL_STUDENTS = 'GET_ALL_STUDENTS'
export const GET_STUDENT_DETAIL = 'GET_STUDENT_DETAIL'
export const POST_STUDENT = 'POST_STUDENT'
export const UPDATE_STUDENT = 'UPDATE_STUDENT'
export const DELETE_STUDENT = 'DELETE_STUDENT'
export const STUDENT_ERROR = 'STUDENT_ERROR'

// TEACHER
export const GET_ALL_TEACHERS = 'GET_ALL_TEACHERS'
export const GET_TEACHER_DETAIL = 'GET_TEACHER_DETAIL'
export const POST_TEACHER = 'POST_TEACHER'
export const UPDATE_TEACHER = 'UPDATE_STUDENT'
export const TEACHER_ERROR = 'TEACHER_ERROR'

export const GET_ALL_COURSES = 'GET_ALL_COURSES'
export const GET_COURSE_DETAIL = 'GET_COURSE_DETAIL'
export const POST_COURSE = 'POST_COURSE'
export const UPDATE_COURSE = 'UPDATE_COURSE'
export const DELETE_COURSE = 'DELETE_COURSE'
export const COURSE_ERROR = 'COURSE_ERROR'