//AUTH ACTION
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const GET_ALL_STUDENTS = 'GET_ALL_STUDENTS'
export const GET_STUDENT_DETAIL = 'GET_STUDENT_DETAIL'
export const POST_STUDENT = 'POST_STUDENT'
export const UPDATE_STUDENT = 'UPDATE_STUDENT'
export const DELETE_STUDENT = 'DELETE_STUDENT'
export const STUDENT_ERROR = 'STUDENT_ERROR'

// TEACHER
export const GET_ALL_TEACHERS = 'GET_ALL_TEACHERS'
export const GET_TEACHER_DETAIL = 'GET_TEACHER_DETAIL'
export const POST_TEACHER = 'POST_TEACHER'
export const UPDATE_TEACHER = 'UPDATE_STUDENT'
export const TEACHER_ERROR = 'TEACHER_ERROR'
export const DELETE_TEACHER = 'DELETE_TEACHER'

export const GET_ALL_COURSES = 'GET_ALL_COURSES'
export const GET_COURSE_DETAIL = 'GET_COURSE_DETAIL'
export const POST_COURSE = 'POST_COURSE'
export const UPDATE_COURSE = 'UPDATE_COURSE'
export const DELETE_COURSE = 'DELETE_COURSE'
export const COURSE_ERROR = 'COURSE_ERROR'


//DEPARTMENT
export const GET_ALL_DEPARTMENTS = 'GET_ALL_DEPARTMENTS'
export const POST_DEPARTMENT = 'POST_DEPARTMENT'
export const DEPARTMENT_ERROR = 'DEPARTMENT_ERROR'
export const DELETE_DEPARTMENT = 'DELETE_DEPARTMENT'
export const UPDATE_DEPARTMENT = 'UPDATE_DEPARTMENT'

// ENROLLMENT
export const GET_ALL_ENROLLMENTS = 'GET_ALL_ENROLLMENTS'
export const POST_ENROLLMENT = 'POST_ENROLLMENT'
export const ENROLLMENT_ERROR = 'ENROLLMENT_ERROR'
export const DELETE_ENROLLMENT = 'DELETE_ENROLLMENT'
export const UPDATE_ENROLLMENT = 'UPDATE_ENROLLMENT'

// COURSE RELEASE
export const GET_ALL_COURSE_RELEASES = 'GET_ALL_COURSE_RELEASES'
export const COURSE_RELEASE_ERROR = 'COURSE_RELEASE_ERROR' 

//APP SETTING
// app
export const APP_TOGGLE_SIDEBAR = "APP_TOGGLE_SIDEBAR";
export const APP_TOGGLE_SETTINGPANEL = "APP_TOGGLE_SETTINGPANEL";