//AUTH ACTION
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const GET_ALL_STUDENTS = 'GET_ALL_STUDENTS'
export const GET_STUDENT_DETAIL = 'GET_STUDENT_DETAIL'
export const DELETE_A_STUDENT = 'DELETE_A_STUDENT'
export const DELETE_MANY_STUDENTS = 'DELETE_MANY_STUDENTS'
export const ADD_STUDENT = 'ADD_STUDENT'
export const UPDATE_STUDENT = 'UPDATE_STUDENT'